services:
  db:
    image: postgres:16
    container_name: opshub_postgres
    environment:
      POSTGRES_USER: opshub
      POSTGRES_PASSWORD: opshub
      POSTGRES_DB: opshub
    ports:
      - "5432:5432"
    volumes:
      - opshub_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: opshub_redis
    ports:
      - "6379:6379"

volumes:
  opshub_pgdata: